@api = http://localhost:3000/tasks 
GET {{api}} 
################################
GET {{api}}/1

#################

GET {{api}}/count

#################

POST {{api}}
Content-Type: application/json

{
    "title": "fifth task",
    "description": "some description task"
}

#################

DELETE {{api}}/5

#################

PUT {{api}}/1
Content-Type: application/json

{
    "title": "Task 1 updated"
}